export default {
  APP_SCOPE: process.env.APP_SCOPE,
  DB_USER_MONGO: process.env.DB_USER_MONGO,
  DB_KEY_MONGO: process.env.DB_KEY_MONGO,
  DB_HOST_MONGO: process.env.DB_HOST_MONGO,
  DB_CONTAINER_NAME_MONGO: process.env.DB_CONTAINER_NAME_MONGO,
  LOGTAIL_SOUCE_TOKEN: process.env.LOGTAIL_SOUCE_TOKEN,
  LOG_LEVEL: process.env.LOG_LEVEL,
  MEMORY_CACHE_KEY: process.env.MEMORY_CACHE_KEY,
};
